### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by iamchristianani** [iamchristianani/drivewise-backend#9]
## Kanban Board Setup for the Final Capstone Project

> Here is the [link](https://github.com/users/iamchristianani/projects/6) to the Kanban Board describing assigned back-end tasks.
> Here is the [link](https://github.com/users/iamchristianani/projects/5) to the Kanban Board describing assigned front-end tasks.

### Team Members (4):
@boo-shehab  (Member A)
@iamchristianani  (Member B)
@RoyJumah  (Member C)
@yuvenalmash  (Member D)

Frontend Kanban Board
![image](https://user-images.githubusercontent.com/116313214/236166625-8a56fd11-49e7-4056-93e5-631dec336bd4.png)

Backend Kanban Board
![image](https://user-images.githubusercontent.com/116313214/236166494-6c77868c-f82c-4be8-8161-5d1da758e237.png)

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Meltrust** [comment]
Hi @iamchristianani,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been pointed and assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

According to the [project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md):

![image](https://user-images.githubusercontent.com/57421823/235993509-cd156f09-d5bd-4921-a93f-43562c690332.png)

At the time of this review, however, these are the pointings, spanning the 2 boards:

@yuvenalmash 8 
@RoyJumah 7
@boo-shehab 19
@iamchristianani 18

The general rule is that nobody can have more than 5 points than any other team member.  That includes the whole team.

As you can see, @boo-shehab and @iamchristianani have 19 and 18 points respectively, while @yuvenalmash and @RoyJumah have 8 and 7.  That's a difference of +26 points, while it shouldn't be more than 5.

Therefore:

- [ ] Kindly, make sure no one in your team has more than 5 points than any other member.  

That way, we will meet this particular requirement. 💪 

_Tip:  You could reassign tasks, move the numbers, change the values._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi team,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now equal, according to the requirement✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
